spring:
    datasource:
        url: jdbc:mysql://localhost:3306/appointment_planner
        username: root
        password: 1lcMNSTR0512002!
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: create